#!/bin/sh

zramCompress=zstd
zramDevice=zram0

# TODO: Check if the user has the following utilities installed `cat`, `grep`, `bc`.

ramSize=$(cat /proc/meminfo | grep -i 'memtotal' | grep -o '[[:digit:]]*' | bc)
zramSize=$(("${ramSize}" / 2))

echo "Creating zram device"
zramctl --algorithm $zramCompress --size ${zramSize}K /dev/${zramDevice}

echo "Formatting zram device for swap usage"
mkswap --uuid clear /dev/${zramDevice}

echo "Enabling zram for swap"
swapon --discard --priority 100 /dev/${zramDevice}
